### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage-physikon#18]
Wir sollten eine FAQ auf der Webseite haben
- [ ] Was ist dieses PeP?
- [ ] Wo ist die Ausstellung?
- [ ] Plan der Umgebung
- [ ] Plan der Messefläche

**Comment by MaxNoe** [comment]
> Wir sollten eine FAQ auf der Webseite haben

Ich bin dagegen.

Wir sollten eher dafür sorgen, dass auf der **Landing Page** diese Fragen übersichtlich beantwortet werden.

**Comment by hmoldenhauer** [comment]
okay, meinetwegen auch das.

**Comment by MaxNoe** [comment]
Die Idee war, eine übersichtliche Landing Page zu haben, die alles wichtige zeigt. 

Verschachtelungen würde ich so weit es geht vermeiden. Die 4 Sachen sind sogar (vielleicht noch nicht optimal) auf der Seite auf einen Blick zu sehen.

Wenn wir jetzt noch eine FAQ Seite machen, haben wir doppelte Buchhaltung und es wird insgesamt unübersichtlicher.

Sobald es wirklich *Frequently Asked Questions* gibt, sollten wir das als Signal nehmen, die Seite in der Hinsicht besser zu machen, nicht einfach die Fragen in einer Liste sammeln.
