### ISSUE TITLE
Online-Anmeldung für Unternehmen

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage-physikon#2]
Vielleicht mit PARS realisierbar?

**Comment by MaxNoe** [comment]
Ich habe gerade mit @lena-lin gesprochen, und wir waren der Meinung, das eine Online-Anmeldung für die Unternehmen nicht viel Sinn macht. Das läuft alles über emails und wir suchen ja die Unternehmen aus, die wir anschreiben.
