### ISSUE TITLE
Online-Anmeldung für Besucher

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/homepage-physikon#3]
Wenn wir einen Messekatalog drucken, sollten wir auch eine online Anmeldung für Besucher machen, damit wir nicht zu viele oder zu wenig Kataloge drucken.

Gerne können auch mehr Besucher kommen, aber die bekommen dann halt keinen Katalog in die Hand gedrückt. Eine pdf-Version dazu sollten wir online stellen

**Comment by jpherdi** [comment]
Wir haben uns für einen Online Katalog entschieden. Das wird auch für die kommenden Jahre sinnvoll bleiben.
